Eggplant.lo: /home/parallels/php/php-7.2.20-ext/ext/Eggplant/Eggplant.c
	$(LIBTOOL) --mode=compile $(CC) -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -I. -I/home/parallels/php/php-7.2.20-ext/ext/Eggplant $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/parallels/php/php-7.2.20-ext/ext/Eggplant/Eggplant.c -o Eggplant.lo 
$(phplibdir)/Eggplant.la: ./Eggplant.la
	$(LIBTOOL) --mode=install cp ./Eggplant.la $(phplibdir)

./Eggplant.la: $(shared_objects_Eggplant) $(EGGPLANT_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS)  -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_Eggplant) $(EGGPLANT_SHARED_LIBADD)

